<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ActeurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ActeurRepository extends EntityRepository
{
    
    public function actorDoesNotExists($acteur){
        $query = $this->createQueryBuilder('a')
                    ->where('a.nomActeur = ?1')
                    ->andWhere('a.prenomActeur = ?2')
                    ->setParameter(1, $acteur->getNomActeur())
                    ->setParameter(2, $acteur->getPrenomActeur())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
