<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
    public function genreDoesNotExists($genre){
        $query = $this->createQueryBuilder('g')
                    ->where('g.ageConseille = ?1')
                    ->andWhere('g.libelleGenre = ?2')
                    ->setParameter(1, $genre->getAgeConseille())
                    ->setParameter(2, $genre->getLibelleGenre())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
