<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Noter_serRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Noter_serRepository extends EntityRepository
{
    public function actorDoesNotExists($noter_ser){
        $query = $this->createQueryBuilder('ns')
                    ->where('ns.note = ?1')
                    ->setParameter(1, $acteur->getNote())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
