<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * Noter_critRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Noter_critRepository extends EntityRepository
{
    public function noter_critDoesNotExists($noter_crit){
        $query = $this->createQueryBuilder('nc')
                    ->where('nc.note = ?1')
                    ->setParameter(1, $noter_crit->getNote())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
