<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ProducteurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProducteurRepository extends EntityRepository
{
    public function producteurDoesNotExists($producteur){
        $query = $this->createQueryBuilder('p')
                    ->where('p.nomProducteur = ?1')
                    ->andWhere('p.prenomProducteur = ?2')
                    ->setParameter(1, $acteur->getNomProducteur())
                    ->setParameter(2, $acteur->getPrenomProducteur())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
