<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RealisateurRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RealisateurRepository extends EntityRepository
{
    public function episodeDoesNotExists($episode){
        $query = $this->createQueryBuilder('r')
                    ->where('r.nomRealisateur = ?1')
                    ->andwhere('r.prenomRealisateur =?2')
                    ->setParameter(1, $episode->getNomRealisateur())
                    ->setParameter(2, $episode->getPrenomRealisateur())
                    ->getQuery();
        $res = $query->getOneOrNullResult();
        
        return !isset($res);
    }
}
