<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * Noter_serRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Noter_serRepository extends EntityRepository
{
}
