src_oc_user:
    resource: "@srcOCUserBundle/Resources/config/routing.xml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
login:
    pattern: /login
    defaults: {_controller: OCUserBundle:Security:login }
    
login_check:
    pattern: /login_check

logout:
    pattern: /logout