# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:
    encoders:
        AppBundle\Entity\Utilisateur:
            algorithm: bcrypt
        
    role_hierarchy:              
        ROLE_ADMIN:       [ROLE_USER,ROLE_AUTEUR,ROLE_MODERATEUR]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN,ROLE_ALLOWED_TO_SWITCH]
        
    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        our_provider:
            entity:
                class: AppBundle:Utilisateur
                property: pseudoUtilisateur
                

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
            
#        main_login:
#            pattern: ^/login$
#            anonymous: true
#            
        main:
            pattern:   ^/
            http_basic: ~
            anonymous: false
            provider: our_provider
            form_login:
                login_path: login
                check_path: login_check
            logout:
                path: logout
                target: /
        default:
            anonymous: ~
            http_basic: ~
#            anonymous: false
#            provider:  my_db
#            form_login:
#                login_path: login
#                check_path: login_check
#            logout:
#                path: logout
#                target: /

            
    access_control:
        - { path: ^/admin$, roles: ROLE_ADMIN }
        

        
            # activate different ways to authenticate

            # http_basic: ~
            # http://symfony.com/doc/current/book/security.html#a-configuring-how-your-users-will-authenticate

            # form_login: ~
            # http://symfony.com/doc/current/cookbook/security/form_login_setup.html
